name: Release Generate

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get current version
        id: version
        run: |
          TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "current_version=${TAG#v}" >> $GITHUB_ENV

      - name: Bump version
        id: bump
        run: |
          IFS='.' read -r major minor patch <<< "${{ env.current_version }}"
          new_patch=$((patch + 1))
          new_version="v$major.$minor.$new_patch"
          echo "new_version=$new_version" >> $GITHUB_ENV

      - name: Create tag
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git tag ${{ env.new_version }}
          git push origin ${{ env.new_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Changelog
        run: |
          git fetch --prune
          PREV_TAG=$(git describe --tags --abbrev=0 ${{ env.new_version }}^ 2>/dev/null || echo "")

          if [ -z "$PREV_TAG" ]; then
            git log --pretty=format:"### %h - %s%n" > CHANGELOG.md
          else
            git log --pretty=format:"### %h - %s%n" $PREV_TAG..${{ env.new_version }} > CHANGELOG.md
          fi

          echo -e "\n## ${{ env.new_version }}\n" | cat - CHANGELOG.md > temp && mv temp CHANGELOG.md
          cat CHANGELOG.md

      - name: Commit Changelog
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add CHANGELOG.md
          git commit -m "docs: update CHANGELOG.md for ${{ env.new_version }}" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.new_version }}
          body_path: CHANGELOG.md
          generate_release_notes: true
