name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  generate-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Changelog
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          git fetch --prune --unshallow  # Garante histórico completo
          echo "## $TAG ($(date +'%Y-%m-%d'))" > CHANGELOG.md
          git log --pretty=format:"- %s" $(git describe --tags --abbrev=0)^..HEAD >> CHANGELOG.md
          echo "" >> CHANGELOG.md
          cat CHANGELOG.md > TEMP && mv TEMP CHANGELOG.md

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.md
          generate_release_notes: true
